# Generated by Django 4.1.2 on 2022-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categories_image',
            field=models.ImageField(default='', upload_to='categories-images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Order Confirmed', 'Order Confirmed'), ('Cancle', 'Cancle')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man')], max_length=10),
        ),
    ]
