# Generated by Django 4.1.2 on 2022-11-07 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_categories_categories_image_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out For Delivery', 'Out For Delivery'), ('Cancle', 'Cancle'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Order Confirmed', 'Order Confirmed')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='FEATURED_PRODUCT',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('gender', models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man')], max_length=10)),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_desc', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.brand')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.categories')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.colour')),
            ],
        ),
    ]
