# Generated by Django 4.1.2 on 2022-11-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0003_alter_order_status_featured_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Order Confirmed', 'Order Confirmed'), ('Cancle', 'Cancle')], default='pending', max_length=50),
        ),
    ]
